# fly.toml app configuration file generated for reactus on 2025-07-23T15:38:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactus'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080 # ← 80 から 8080 に変更
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

    [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/"
    grace_period = "20s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256